#include "pinyinmap.h"

map<string, int32_t> initPhoneIDMap()
{
    map<string, int32_t> phoneIDMap={
{"sil",0},
{"eos",1},
{"sp",2},
{"#0",3},
{"#1",4},
{"#2",5},
{"#3",6},
{"^",7},
{"b",8},
{"c",9},
{"ch",10},
{"d",11},
{"f",12},
{"g",13},
{"h",14},
{"j",15},
{"k",16},
{"l",17},
{"m",18},
{"n",19},
{"p",20},
{"q",21},
{"r",22},
{"s",23},
{"sh",24},
{"t",25},
{"x",26},
{"z",27},
{"zh",28},
{"a1",29},
{"a2",30},
{"a3",31},
{"a4",32},
{"a5",33},
{"ai1",34},
{"ai2",35},
{"ai3",36},
{"ai4",37},
{"ai5",38},
{"an1",39},
{"an2",40},
{"an3",41},
{"an4",42},
{"an5",43},
{"ang1",44},
{"ang2",45},
{"ang3",46},
{"ang4",47},
{"ang5",48},
{"ao1",49},
{"ao2",50},
{"ao3",51},
{"ao4",52},
{"ao5",53},
{"e1",54},
{"e2",55},
{"e3",56},
{"e4",57},
{"e5",58},
{"ei1",59},
{"ei2",60},
{"ei3",61},
{"ei4",62},
{"ei5",63},
{"en1",64},
{"en2",65},
{"en3",66},
{"en4",67},
{"en5",68},
{"eng1",69},
{"eng2",70},
{"eng3",71},
{"eng4",72},
{"eng5",73},
{"er1",74},
{"er2",75},
{"er3",76},
{"er4",77},
{"er5",78},
{"i1",79},
{"i2",80},
{"i3",81},
{"i4",82},
{"i5",83},
{"ia1",84},
{"ia2",85},
{"ia3",86},
{"ia4",87},
{"ia5",88},
{"ian1",89},
{"ian2",90},
{"ian3",91},
{"ian4",92},
{"ian5",93},
{"iang1",94},
{"iang2",95},
{"iang3",96},
{"iang4",97},
{"iang5",98},
{"iao1",99},
{"iao2",100},
{"iao3",101},
{"iao4",102},
{"iao5",103},
{"ie1",104},
{"ie2",105},
{"ie3",106},
{"ie4",107},
{"ie5",108},
{"ii1",109},
{"ii2",110},
{"ii3",111},
{"ii4",112},
{"ii5",113},
{"iii1",114},
{"iii2",115},
{"iii3",116},
{"iii4",117},
{"iii5",118},
{"in1",119},
{"in2",120},
{"in3",121},
{"in4",122},
{"in5",123},
{"ing1",124},
{"ing2",125},
{"ing3",126},
{"ing4",127},
{"ing5",128},
{"iong1",129},
{"iong2",130},
{"iong3",131},
{"iong4",132},
{"iong5",133},
{"iou1",134},
{"iou2",135},
{"iou3",136},
{"iou4",137},
{"iou5",138},
{"o1",139},
{"o2",140},
{"o3",141},
{"o4",142},
{"o5",143},
{"ong1",144},
{"ong2",145},
{"ong3",146},
{"ong4",147},
{"ong5",148},
{"ou1",149},
{"ou2",150},
{"ou3",151},
{"ou4",152},
{"ou5",153},
{"u1",154},
{"u2",155},
{"u3",156},
{"u4",157},
{"u5",158},
{"ua1",159},
{"ua2",160},
{"ua3",161},
{"ua4",162},
{"ua5",163},
{"uai1",164},
{"uai2",165},
{"uai3",166},
{"uai4",167},
{"uai5",168},
{"uan1",169},
{"uan2",170},
{"uan3",171},
{"uan4",172},
{"uan5",173},
{"uang1",174},
{"uang2",175},
{"uang3",176},
{"uang4",177},
{"uang5",178},
{"uei1",179},
{"uei2",180},
{"uei3",181},
{"uei4",182},
{"uei5",183},
{"uen1",184},
{"uen2",185},
{"uen3",186},
{"uen4",187},
{"uen5",188},
{"ueng1",189},
{"ueng2",190},
{"ueng3",191},
{"ueng4",192},
{"ueng5",193},
{"uo1",194},
{"uo2",195},
{"uo3",196},
{"uo4",197},
{"uo5",198},
{"v1",199},
{"v2",200},
{"v3",201},
{"v4",202},
{"v5",203},
{"van1",204},
{"van2",205},
{"van3",206},
{"van4",207},
{"van5",208},
{"ve1",209},
{"ve2",210},
{"ve3",211},
{"ve4",212},
{"ve5",213},
{"vn1",214},
{"vn2",215},
{"vn3",216},
{"vn4",217},
{"vn5",218}};

    return phoneIDMap;
}

map<uint16_t, uint16_t> initNumMap()
{
    map<uint16_t,uint16_t> numMap={
    {0x31,0x4e00},
    {0x32,0x4e8c},
    {0x33,0x4e09},
    {0x34,0x56db}
    {0x35,0x4e94},
    {0x36,0x516d},
    {0x37,0x4e03},
    {0x38,0x516b},
    {0x39,0x4e5d},
    {0x30,0x96f6}};

    return numMap;
    
}


multimap<string, vector<string> > initPinyin2Phone()
{

    multimap<string, vector<string>> pingyin2PhoneMap={
    {pair<string, vector<string>>("a", vector<string>({"^", "a"}))},
    {pair<string, vector<string>>("ai",vector<string>({"^", "ai"}))},
    {pair<string, vector<string>>("ai", vector<string>({"^", "ai"}))},
    {pair<string, vector<string>>("an", vector<string>({"^", "an"}))},
    {pair<string, vector<string>>("ang", vector<string>({"^", "ang"}))},
    {pair<string, vector<string>>("ao", vector<string>({"^", "ao"}))},
    {pair<string, vector<string>>("ba", vector<string>({"b", "a"}))},
    {pair<string, vector<string>>("bai", vector<string>({"b", "ai"}))},
    {pair<string, vector<string>>("ban", vector<string>({"b", "an"}))},
    {pair<string, vector<string>>("bang", vector<string>({"b", "ang"}))},
    {pair<string, vector<string>>("bao", vector<string>({"b", "ao"}))},
    {pair<string, vector<string>>("be", vector<string>({"b", "e"}))},
    {pair<string, vector<string>>("bei", vector<string>({"b", "ei"}))},
    {pair<string, vector<string>>("ben", vector<string>({"b", "en"}))},
    {pair<string, vector<string>>("beng", vector<string>({"b", "eng"}))},
    {pair<string, vector<string>>("bi", vector<string>({"b", "i"}))},
    {pair<string, vector<string>>("bian", vector<string>({"b", "ian"}))},
    {pair<string, vector<string>>("biao", vector<string>({"b", "iao"}))},
    {pair<string, vector<string>>("bie", vector<string>({"b", "ie"}))},
    {pair<string, vector<string>>("bin", vector<string>({"b", "in"}))},
    {pair<string, vector<string>>("bing", vector<string>({"b", "ing"}))},
    {pair<string, vector<string>>("bo", vector<string>({"b", "o"}))},
    {pair<string, vector<string>>("bu", vector<string>({"b", "u"}))},
    {pair<string, vector<string>>("ca", vector<string>({"c", "a"}))},
    {pair<string, vector<string>>("cai", vector<string>({"c", "ai"}))},
    {pair<string, vector<string>>("can", vector<string>({"c", "an"}))},
    {pair<string, vector<string>>("cang", vector<string>({"c", "ang"}))},
    {pair<string, vector<string>>("cao", vector<string>({"c", "ao"}))},
    {pair<string, vector<string>>("ce", vector<string>({"c", "e"}))},
    {pair<string, vector<string>>("cen", vector<string>({"c", "en"}))},
    {pair<string, vector<string>>("ceng", vector<string>({"c", "eng"}))},
    {pair<string, vector<string>>("cha", vector<string>({"ch", "a"}))},
    {pair<string, vector<string>>("chai", vector<string>({"ch", "ai"}))},
    {pair<string, vector<string>>("chan", vector<string>({"ch", "an"}))},
    {pair<string, vector<string>>("chang", vector<string>({"ch", "ang"}))},
    {pair<string, vector<string>>("chao", vector<string>({"ch", "ao"}))},
    {pair<string, vector<string>>("che", vector<string>({"ch", "e"}))},
    {pair<string, vector<string>>("chen", vector<string>({"ch", "en"}))},
    {pair<string, vector<string>>("cheng", vector<string>({"ch", "eng"}))},
    {pair<string, vector<string>>("chi", vector<string>({"ch", "iii"}))},
    {pair<string, vector<string>>("chong", vector<string>({"ch", "ong"}))},
    {pair<string, vector<string>>("chou", vector<string>({"ch", "ou"}))},
    {pair<string, vector<string>>("chu", vector<string>({"ch", "u"}))},
    {pair<string, vector<string>>("chua", vector<string>({"ch", "ua"}))},
    {pair<string, vector<string>>("chuai", vector<string>({"ch", "uai"}))},
    {pair<string, vector<string>>("chuan", vector<string>({"ch", "uan"}))},
    {pair<string, vector<string>>("chuang", vector<string>({"ch", "uang"}))},
    {pair<string, vector<string>>("chui", vector<string>({"ch", "uei"}))},
    {pair<string, vector<string>>("chun", vector<string>({"ch", "uen"}))},
    {pair<string, vector<string>>("chuo", vector<string>({"ch", "uo"}))},
    {pair<string, vector<string>>("ci", vector<string>({"c", "ii"}))},
    {pair<string, vector<string>>("cong", vector<string>({"c", "ong"}))},
    {pair<string, vector<string>>("cou", vector<string>({"c", "ou"}))},
    {pair<string, vector<string>>("cu", vector<string>({"c", "u"}))},
    {pair<string, vector<string>>("cuan", vector<string>({"c", "uan"}))},
    {pair<string, vector<string>>("cui", vector<string>({"c", "uei"}))},
    {pair<string, vector<string>>("cun", vector<string>({"c", "uen"}))},
    {pair<string, vector<string>>("cuo", vector<string>({"c", "uo"}))},
    {pair<string, vector<string>>("da", vector<string>({"d", "a"}))},
    {pair<string, vector<string>>("dai", vector<string>({"d", "ai"}))},
    {pair<string, vector<string>>("dan", vector<string>({"d", "an"}))},
    {pair<string, vector<string>>("dang", vector<string>({"d", "ang"}))},
    {pair<string, vector<string>>("dao", vector<string>({"d", "ao"}))},
    {pair<string, vector<string>>("de", vector<string>({"d", "e"}))},
    {pair<string, vector<string>>("dei", vector<string>({"d", "ei"}))},
    {pair<string, vector<string>>("den", vector<string>({"d", "en"}))},
    {pair<string, vector<string>>("deng", vector<string>({"d", "eng"}))},
    {pair<string, vector<string>>("di", vector<string>({"d", "i"}))},
    {pair<string, vector<string>>("dia", vector<string>({"d", "ia"}))},
    {pair<string, vector<string>>("dian", vector<string>({"d", "ian"}))},
    {pair<string, vector<string>>("diao", vector<string>({"d", "iao"}))},
    {pair<string, vector<string>>("die", vector<string>({"d", "ie"}))},
    {pair<string, vector<string>>("ding", vector<string>({"d", "ing"}))},
    {pair<string, vector<string>>("diu", vector<string>({"d", "iou"}))},
    {pair<string, vector<string>>("dong", vector<string>({"d", "ong"}))},
    {pair<string, vector<string>>("dou", vector<string>({"d", "ou"}))},
    {pair<string, vector<string>>("du", vector<string>({"d", "u"}))},
    {pair<string, vector<string>>("duan", vector<string>({"d", "uan"}))},
    {pair<string, vector<string>>("dui", vector<string>({"d", "uei"}))},
    {pair<string, vector<string>>("dun", vector<string>({"d", "uen"}))},
    {pair<string, vector<string>>("duo", vector<string>({"d", "uo"}))},
    {pair<string, vector<string>>("e", vector<string>({"^", "e"}))},
    {pair<string, vector<string>>("ei", vector<string>({"^", "ei"}))},
    {pair<string, vector<string>>("en", vector<string>({"^", "en"}))},
    {pair<string, vector<string>>("ng", vector<string>({"^", "en"}))},
    {pair<string, vector<string>>("eng", vector<string>({"^", "eng"}))},
    {pair<string, vector<string>>("er", vector<string>({"^", "er"}))},
    {pair<string, vector<string>>("fa", vector<string>({"f", "a"}))},
    {pair<string, vector<string>>("fan", vector<string>({"f", "an"}))},
    {pair<string, vector<string>>("fang", vector<string>({"f", "ang"}))},
    {pair<string, vector<string>>("fei", vector<string>({"f", "ei"}))},
    {pair<string, vector<string>>("fen", vector<string>({"f", "en"}))},
    {pair<string, vector<string>>("feng", vector<string>({"f", "eng"}))},
    {pair<string, vector<string>>("fo", vector<string>({"f", "o"}))},
    {pair<string, vector<string>>("fou", vector<string>({"f", "ou"}))},
    {pair<string, vector<string>>("fu", vector<string>({"f", "u"}))},
    {pair<string, vector<string>>("ga", vector<string>({"g", "a"}))},
    {pair<string, vector<string>>("gai", vector<string>({"g", "ai"}))},
    {pair<string, vector<string>>("gan", vector<string>({"g", "an"}))},
    {pair<string, vector<string>>("gang", vector<string>({"g", "ang"}))},
    {pair<string, vector<string>>("gao", vector<string>({"g", "ao"}))},
    {pair<string, vector<string>>("ge", vector<string>({"g", "e"}))},
    {pair<string, vector<string>>("gei", vector<string>({"g", "ei"}))},
    {pair<string, vector<string>>("gen", vector<string>({"g", "en"}))},
    {pair<string, vector<string>>("geng", vector<string>({"g", "eng"}))},
    {pair<string, vector<string>>("gong", vector<string>({"g", "ong"}))},
    {pair<string, vector<string>>("gou", vector<string>({"g", "ou"}))},
    {pair<string, vector<string>>("gu", vector<string>({"g", "u"}))},
    {pair<string, vector<string>>("gua", vector<string>({"g", "ua"}))},
    {pair<string, vector<string>>("guai", vector<string>({"g", "uai"}))},
    {pair<string, vector<string>>("guan", vector<string>({"g", "uan"}))},
    {pair<string, vector<string>>("guang", vector<string>({"g", "uang"}))},
    {pair<string, vector<string>>("gui", vector<string>({"g", "uei"}))},
    {pair<string, vector<string>>("gun", vector<string>({"g", "uen"}))},
    {pair<string, vector<string>>("guo", vector<string>({"g", "uo"}))},
    {pair<string, vector<string>>("ha", vector<string>({"h", "a"}))},
    {pair<string, vector<string>>("hai", vector<string>({"h", "ai"}))},
    {pair<string, vector<string>>("han", vector<string>({"h", "an"}))},
    {pair<string, vector<string>>("hang", vector<string>({"h", "ang"}))},
    {pair<string, vector<string>>("hao", vector<string>({"h", "ao"}))},
    {pair<string, vector<string>>("he", vector<string>({"h", "e"}))},
    {pair<string, vector<string>>("hei", vector<string>({"h", "ei"}))},
    {pair<string, vector<string>>("hen", vector<string>({"h", "en"}))},
    {pair<string, vector<string>>("heng", vector<string>({"h", "eng"}))},
    {pair<string, vector<string>>("hong", vector<string>({"h", "ong"}))},
    {pair<string, vector<string>>("hou", vector<string>({"h", "ou"}))},
    {pair<string, vector<string>>("hu", vector<string>({"h", "u"}))},
    {pair<string, vector<string>>("hua", vector<string>({"h", "ua"}))},
    {pair<string, vector<string>>("huai", vector<string>({"h", "uai"}))},
    {pair<string, vector<string>>("huan", vector<string>({"h", "uan"}))},
    {pair<string, vector<string>>("huang", vector<string>({"h", "uang"}))},
    {pair<string, vector<string>>("hui", vector<string>({"h", "uei"}))},
    {pair<string, vector<string>>("hun", vector<string>({"h", "uen"}))},
    {pair<string, vector<string>>("huo", vector<string>({"h", "uo"}))},
    {pair<string, vector<string>>("ji", vector<string>({"j", "i"}))},
    {pair<string, vector<string>>("jia", vector<string>({"j", "ia"}))},
    {pair<string, vector<string>>("jian", vector<string>({"j", "ian"}))},
    {pair<string, vector<string>>("jiang", vector<string>({"j", "iang"}))},
    {pair<string, vector<string>>("jiao", vector<string>({"j", "iao"}))},
    {pair<string, vector<string>>("jie", vector<string>({"j", "ie"}))},
    {pair<string, vector<string>>("jin", vector<string>({"j", "in"}))},
    {pair<string, vector<string>>("jing", vector<string>({"j", "ing"}))},
    {pair<string, vector<string>>("jiong", vector<string>({"j", "iong"}))},
    {pair<string, vector<string>>("jiu", vector<string>({"j", "iou"}))},
    {pair<string, vector<string>>("ju", vector<string>({"j", "v"}))},
    {pair<string, vector<string>>("juan", vector<string>({"j", "van"}))},
    {pair<string, vector<string>>("jue", vector<string>({"j", "ve"}))},
    {pair<string, vector<string>>("jun", vector<string>({"j", "vn"}))},
    {pair<string, vector<string>>("ka", vector<string>({"k", "a"}))},
    {pair<string, vector<string>>("kai", vector<string>({"k", "ai"}))},
    {pair<string, vector<string>>("kan", vector<string>({"k", "an"}))},
    {pair<string, vector<string>>("kang", vector<string>({"k", "ang"}))},
    {pair<string, vector<string>>("kao", vector<string>({"k", "ao"}))},
    {pair<string, vector<string>>("ke", vector<string>({"k", "e"}))},
    {pair<string, vector<string>>("kei", vector<string>({"k", "ei"}))},
    {pair<string, vector<string>>("ken", vector<string>({"k", "en"}))},
    {pair<string, vector<string>>("keng", vector<string>({"k", "eng"}))},
    {pair<string, vector<string>>("kong", vector<string>({"k", "ong"}))},
    {pair<string, vector<string>>("kou", vector<string>({"k", "ou"}))},
    {pair<string, vector<string>>("ku", vector<string>({"k", "u"}))},
    {pair<string, vector<string>>("kua", vector<string>({"k", "ua"}))},
    {pair<string, vector<string>>("kuai", vector<string>({"k", "uai"}))},
    {pair<string, vector<string>>("kuan", vector<string>({"k", "uan"}))},
    {pair<string, vector<string>>("kuang", vector<string>({"k", "uang"}))},
    {pair<string, vector<string>>("kui", vector<string>({"k", "uei"}))},
    {pair<string, vector<string>>("kun", vector<string>({"k", "uen"}))},
    {pair<string, vector<string>>("kuo", vector<string>({"k", "uo"}))},
    {pair<string, vector<string>>("la", vector<string>({"l", "a"}))},
    {pair<string, vector<string>>("lai", vector<string>({"l", "ai"}))},
    {pair<string, vector<string>>("lan", vector<string>({"l", "an"}))},
    {pair<string, vector<string>>("lang", vector<string>({"l", "ang"}))},
    {pair<string, vector<string>>("lao", vector<string>({"l", "ao"}))},
    {pair<string, vector<string>>("le", vector<string>({"l", "e"}))},
    {pair<string, vector<string>>("lei", vector<string>({"l", "ei"}))},
    {pair<string, vector<string>>("leng", vector<string>({"l", "eng"}))},
    {pair<string, vector<string>>("li", vector<string>({"l", "i"}))},
    {pair<string, vector<string>>("lia", vector<string>({"l", "ia"}))},
    {pair<string, vector<string>>("lian", vector<string>({"l", "ian"}))},
    {pair<string, vector<string>>("liang", vector<string>({"l", "iang"}))},
    {pair<string, vector<string>>("liao", vector<string>({"l", "iao"}))},
    {pair<string, vector<string>>("lie", vector<string>({"l", "ie"}))},
    {pair<string, vector<string>>("lin", vector<string>({"l", "in"}))},
    {pair<string, vector<string>>("ling", vector<string>({"l", "ing"}))},
    {pair<string, vector<string>>("liu", vector<string>({"l", "iou"}))},
    {pair<string, vector<string>>("lo", vector<string>({"l", "o"}))},
    {pair<string, vector<string>>("long", vector<string>({"l", "ong"}))},
    {pair<string, vector<string>>("lou", vector<string>({"l", "ou"}))},
    {pair<string, vector<string>>("lu", vector<string>({"l", "u"}))},
    {pair<string, vector<string>>("lv", vector<string>({"l", "v"}))},
    {pair<string, vector<string>>("luan", vector<string>({"l", "uan"}))},
    {pair<string, vector<string>>("lve", vector<string>({"l", "ve"}))},
    {pair<string, vector<string>>("lue", vector<string>({"l", "ve"}))},
    {pair<string, vector<string>>("lun", vector<string>({"l", "uen"}))},
    {pair<string, vector<string>>("luo", vector<string>({"l", "uo"}))},
    {pair<string, vector<string>>("ma", vector<string>({"m", "a"}))},
    {pair<string, vector<string>>("mai", vector<string>({"m", "ai"}))},
    {pair<string, vector<string>>("man", vector<string>({"m", "an"}))},
    {pair<string, vector<string>>("mang", vector<string>({"m", "ang"}))},
    {pair<string, vector<string>>("mao", vector<string>({"m", "ao"}))},
    {pair<string, vector<string>>("me", vector<string>({"m", "e"}))},
    {pair<string, vector<string>>("mei", vector<string>({"m", "ei"}))},
    {pair<string, vector<string>>("men", vector<string>({"m", "en"}))},
    {pair<string, vector<string>>("meng", vector<string>({"m", "eng"}))},
    {pair<string, vector<string>>("mi", vector<string>({"m", "i"}))},
    {pair<string, vector<string>>("mian", vector<string>({"m", "ian"}))},
    {pair<string, vector<string>>("miao", vector<string>({"m", "iao"}))},
    {pair<string, vector<string>>("mie", vector<string>({"m", "ie"}))},
    {pair<string, vector<string>>("min", vector<string>({"m", "in"}))},
    {pair<string, vector<string>>("ming", vector<string>({"m", "ing"}))},
    {pair<string, vector<string>>("miu", vector<string>({"m", "iou"}))},
    {pair<string, vector<string>>("mo", vector<string>({"m", "o"}))},
    {pair<string, vector<string>>("mou", vector<string>({"m", "ou"}))},
    {pair<string, vector<string>>("mu", vector<string>({"m", "u"}))},
    {pair<string, vector<string>>("na", vector<string>({"n", "a"}))},
    {pair<string, vector<string>>("nai", vector<string>({"n", "ai"}))},
    {pair<string, vector<string>>("nan", vector<string>({"n", "an"}))},
    {pair<string, vector<string>>("nang", vector<string>({"n", "ang"}))},
    {pair<string, vector<string>>("nao", vector<string>({"n", "ao"}))},
    {pair<string, vector<string>>("ne", vector<string>({"n", "e"}))},
    {pair<string, vector<string>>("nei", vector<string>({"n", "ei"}))},
    {pair<string, vector<string>>("nen", vector<string>({"n", "en"}))},
    {pair<string, vector<string>>("neng", vector<string>({"n", "eng"}))},
    {pair<string, vector<string>>("ni", vector<string>({"n", "i"}))},
    {pair<string, vector<string>>("nia", vector<string>({"n", "ia"}))},
    {pair<string, vector<string>>("nian", vector<string>({"n", "ian"}))},
    {pair<string, vector<string>>("niang", vector<string>({"n", "iang"}))},
    {pair<string, vector<string>>("niao", vector<string>({"n", "iao"}))},
    {pair<string, vector<string>>("nie", vector<string>({"n", "ie"}))},
    {pair<string, vector<string>>("nin", vector<string>({"n", "in"}))},
    {pair<string, vector<string>>("ning", vector<string>({"n", "ing"}))},
    {pair<string, vector<string>>("niu", vector<string>({"n", "iou"}))},
    {pair<string, vector<string>>("nong", vector<string>({"n", "ong"}))},
    {pair<string, vector<string>>("nou", vector<string>({"n", "ou"}))},
    {pair<string, vector<string>>("nu", vector<string>({"n", "u"}))},
    {pair<string, vector<string>>("nv", vector<string>({"n", "v"}))},
    {pair<string, vector<string>>("nuan", vector<string>({"n", "uan"}))},
    {pair<string, vector<string>>("nve", vector<string>({"n", "ve"}))},
    {pair<string, vector<string>>("nue", vector<string>({"n", "ve"}))},
    {pair<string, vector<string>>("nuo", vector<string>({"n", "uo"}))},
    {pair<string, vector<string>>("o", vector<string>({"^", "o"}))},
    {pair<string, vector<string>>("ou", vector<string>({"^", "ou"}))},
    {pair<string, vector<string>>("pa", vector<string>({"p", "a"}))},
    {pair<string, vector<string>>("pai", vector<string>({"p", "ai"}))},
    {pair<string, vector<string>>("pan", vector<string>({"p", "an"}))},
    {pair<string, vector<string>>("pang", vector<string>({"p", "ang"}))},
    {pair<string, vector<string>>("pao", vector<string>({"p", "ao"}))},
    {pair<string, vector<string>>("pe", vector<string>({"p", "e"}))},
    {pair<string, vector<string>>("pei", vector<string>({"p", "ei"}))},
    {pair<string, vector<string>>("pen", vector<string>({"p", "en"}))},
    {pair<string, vector<string>>("peng", vector<string>({"p", "eng"}))},
    {pair<string, vector<string>>("pi", vector<string>({"p", "i"}))},
    {pair<string, vector<string>>("pian", vector<string>({"p", "ian"}))},
    {pair<string, vector<string>>("piao", vector<string>({"p", "iao"}))},
    {pair<string, vector<string>>("pie", vector<string>({"p", "ie"}))},
    {pair<string, vector<string>>("pin", vector<string>({"p", "in"}))},
    {pair<string, vector<string>>("ping", vector<string>({"p", "ing"}))},
    {pair<string, vector<string>>("po", vector<string>({"p", "o"}))},
    {pair<string, vector<string>>("pou", vector<string>({"p", "ou"}))},
    {pair<string, vector<string>>("pu", vector<string>({"p", "u"}))},
    {pair<string, vector<string>>("qi", vector<string>({"q", "i"}))},
    {pair<string, vector<string>>("qia", vector<string>({"q", "ia"}))},
    {pair<string, vector<string>>("qian", vector<string>({"q", "ian"}))},
    {pair<string, vector<string>>("qiang", vector<string>({"q", "iang"}))},
    {pair<string, vector<string>>("qiao", vector<string>({"q", "iao"}))},
    {pair<string, vector<string>>("qie", vector<string>({"q", "ie"}))},
    {pair<string, vector<string>>("qin", vector<string>({"q", "in"}))},
    {pair<string, vector<string>>("qing", vector<string>({"q", "ing"}))},
    {pair<string, vector<string>>("qiong", vector<string>({"q", "iong"}))},
    {pair<string, vector<string>>("qiu", vector<string>({"q", "iou"}))},
    {pair<string, vector<string>>("qu", vector<string>({"q", "v"}))},
    {pair<string, vector<string>>("quan", vector<string>({"q", "van"}))},
    {pair<string, vector<string>>("que", vector<string>({"q", "ve"}))},
    {pair<string, vector<string>>("qun", vector<string>({"q", "vn"}))},
    {pair<string, vector<string>>("ran", vector<string>({"r", "an"}))},
    {pair<string, vector<string>>("rang", vector<string>({"r", "ang"}))},
    {pair<string, vector<string>>("rao", vector<string>({"r", "ao"}))},
    {pair<string, vector<string>>("re", vector<string>({"r", "e"}))},
    {pair<string, vector<string>>("ren", vector<string>({"r", "en"}))},
    {pair<string, vector<string>>("reng", vector<string>({"r", "eng"}))},
    {pair<string, vector<string>>("ri", vector<string>({"r", "iii"}))},
    {pair<string, vector<string>>("rong", vector<string>({"r", "ong"}))},
    {pair<string, vector<string>>("rou", vector<string>({"r", "ou"}))},
    {pair<string, vector<string>>("ru", vector<string>({"r", "u"}))},
    {pair<string, vector<string>>("rua", vector<string>({"r", "ua"}))},
    {pair<string, vector<string>>("ruan", vector<string>({"r", "uan"}))},
    {pair<string, vector<string>>("rui", vector<string>({"r", "uei"}))},
    {pair<string, vector<string>>("run", vector<string>({"r", "uen"}))},
    {pair<string, vector<string>>("ruo", vector<string>({"r", "uo"}))},
    {pair<string, vector<string>>("sa", vector<string>({"s", "a"}))},
    {pair<string, vector<string>>("sai", vector<string>({"s", "ai"}))},
    {pair<string, vector<string>>("san", vector<string>({"s", "an"}))},
    {pair<string, vector<string>>("sang", vector<string>({"s", "ang"}))},
    {pair<string, vector<string>>("sao", vector<string>({"s", "ao"}))},
    {pair<string, vector<string>>("se", vector<string>({"s", "e"}))},
    {pair<string, vector<string>>("sen", vector<string>({"s", "en"}))},
    {pair<string, vector<string>>("seng", vector<string>({"s", "eng"}))},
    {pair<string, vector<string>>("sha", vector<string>({"sh", "a"}))},
    {pair<string, vector<string>>("shai", vector<string>({"sh", "ai"}))},
    {pair<string, vector<string>>("shan", vector<string>({"sh", "an"}))},
    {pair<string, vector<string>>("shang", vector<string>({"sh", "ang"}))},
    {pair<string, vector<string>>("shao", vector<string>({"sh", "ao"}))},
    {pair<string, vector<string>>("she", vector<string>({"sh", "e"}))},
    {pair<string, vector<string>>("shei", vector<string>({"sh", "ei"}))},
    {pair<string, vector<string>>("shen", vector<string>({"sh", "en"}))},
    {pair<string, vector<string>>("sheng", vector<string>({"sh", "eng"}))},
    {pair<string, vector<string>>("shi", vector<string>({"sh", "iii"}))},
    {pair<string, vector<string>>("shou", vector<string>({"sh", "ou"}))},
    {pair<string, vector<string>>("shu", vector<string>({"sh", "u"}))},
    {pair<string, vector<string>>("shua", vector<string>({"sh", "ua"}))},
    {pair<string, vector<string>>("shuai", vector<string>({"sh", "uai"}))},
    {pair<string, vector<string>>("shuan", vector<string>({"sh", "uan"}))},
    {pair<string, vector<string>>("shuang", vector<string>({"sh", "uang"}))},
    {pair<string, vector<string>>("shui", vector<string>({"sh", "uei"}))},
    {pair<string, vector<string>>("shun", vector<string>({"sh", "uen"}))},
    {pair<string, vector<string>>("shuo", vector<string>({"sh", "uo"}))},
    {pair<string, vector<string>>("si", vector<string>({"s", "ii"}))},
    {pair<string, vector<string>>("song", vector<string>({"s", "ong"}))},
    {pair<string, vector<string>>("sou", vector<string>({"s", "ou"}))},
    {pair<string, vector<string>>("su", vector<string>({"s", "u"}))},
    {pair<string, vector<string>>("suan", vector<string>({"s", "uan"}))},
    {pair<string, vector<string>>("sui", vector<string>({"s", "uei"}))},
    {pair<string, vector<string>>("sun", vector<string>({"s", "uen"}))},
    {pair<string, vector<string>>("suo", vector<string>({"s", "uo"}))},
    {pair<string, vector<string>>("ta", vector<string>({"t", "a"}))},
    {pair<string, vector<string>>("tai", vector<string>({"t", "ai"}))},
    {pair<string, vector<string>>("tan", vector<string>({"t", "an"}))},
    {pair<string, vector<string>>("tang", vector<string>({"t", "ang"}))},
    {pair<string, vector<string>>("tao", vector<string>({"t", "ao"}))},
    {pair<string, vector<string>>("te", vector<string>({"t", "e"}))},
    {pair<string, vector<string>>("tei", vector<string>({"t", "ei"}))},
    {pair<string, vector<string>>("teng", vector<string>({"t", "eng"}))},
    {pair<string, vector<string>>("ti", vector<string>({"t", "i"}))},
    {pair<string, vector<string>>("tian", vector<string>({"t", "ian"}))},
    {pair<string, vector<string>>("tiao", vector<string>({"t", "iao"}))},
    {pair<string, vector<string>>("tie", vector<string>({"t", "ie"}))},
    {pair<string, vector<string>>("ting", vector<string>({"t", "ing"}))},
    {pair<string, vector<string>>("tong", vector<string>({"t", "ong"}))},
    {pair<string, vector<string>>("tou", vector<string>({"t", "ou"}))},
    {pair<string, vector<string>>("tu", vector<string>({"t", "u"}))},
    {pair<string, vector<string>>("tuan", vector<string>({"t", "uan"}))},
    {pair<string, vector<string>>("tui", vector<string>({"t", "uei"}))},
    {pair<string, vector<string>>("tun", vector<string>({"t", "uen"}))},
    {pair<string, vector<string>>("tuo", vector<string>({"t", "uo"}))},
    {pair<string, vector<string>>("wa", vector<string>({"^", "ua"}))},
    {pair<string, vector<string>>("wai", vector<string>({"^", "uai"}))},
    {pair<string, vector<string>>("wan", vector<string>({"^", "uan"}))},
    {pair<string, vector<string>>("wang", vector<string>({"^", "uang"}))},
    {pair<string, vector<string>>("wei", vector<string>({"^", "uei"}))},
    {pair<string, vector<string>>("wen", vector<string>({"^", "uen"}))},
    {pair<string, vector<string>>("weng", vector<string>({"^", "ueng"}))},
    {pair<string, vector<string>>("wo", vector<string>({"^", "uo"}))},
    {pair<string, vector<string>>("wu", vector<string>({"^", "u"}))},
    {pair<string, vector<string>>("xi", vector<string>({"x", "i"}))},
    {pair<string, vector<string>>("xia", vector<string>({"x", "ia"}))},
    {pair<string, vector<string>>("xian", vector<string>({"x", "ian"}))},
    {pair<string, vector<string>>("xiang", vector<string>({"x", "iang"}))},
    {pair<string, vector<string>>("xiao", vector<string>({"x", "iao"}))},
    {pair<string, vector<string>>("xie", vector<string>({"x", "ie"}))},
    {pair<string, vector<string>>("xin", vector<string>({"x", "in"}))},
    {pair<string, vector<string>>("xing", vector<string>({"x", "ing"}))},
    {pair<string, vector<string>>("xiong", vector<string>({"x", "iong"}))},
    {pair<string, vector<string>>("xiu", vector<string>({"x", "iou"}))},
    {pair<string, vector<string>>("xu", vector<string>({"x", "v"}))},
    {pair<string, vector<string>>("xuan", vector<string>({"x", "van"}))},
    {pair<string, vector<string>>("xue", vector<string>({"x", "ve"}))},
    {pair<string, vector<string>>("xun", vector<string>({"x", "vn"}))},
    {pair<string, vector<string>>("ya", vector<string>({"^", "ia"}))},
    {pair<string, vector<string>>("yan", vector<string>({"^", "ian"}))},
    {pair<string, vector<string>>("yang", vector<string>({"^", "iang"}))},
    {pair<string, vector<string>>("yao", vector<string>({"^", "iao"}))},
    {pair<string, vector<string>>("ye", vector<string>({"^", "ie"}))},
    {pair<string, vector<string>>("yi", vector<string>({"^", "i"}))},
    {pair<string, vector<string>>("yin", vector<string>({"^", "in"}))},
    {pair<string, vector<string>>("ying", vector<string>({"^", "ing"}))},
    {pair<string, vector<string>>("yo", vector<string>({"^", "iou"}))},
    {pair<string, vector<string>>("yong", vector<string>({"^", "iong"}))},
    {pair<string, vector<string>>("you", vector<string>({"^", "iou"}))},
    {pair<string, vector<string>>("yu", vector<string>({"^", "v"}))},
    {pair<string, vector<string>>("yuan", vector<string>({"^", "van"}))},
    {pair<string, vector<string>>("yue", vector<string>({"^", "ve"}))},
    {pair<string, vector<string>>("yun", vector<string>({"^", "vn"}))},
    {pair<string, vector<string>>("za", vector<string>({"z", "a"}))},
    {pair<string, vector<string>>("zai", vector<string>({"z", "ai"}))},
    {pair<string, vector<string>>("zan", vector<string>({"z", "an"}))},
    {pair<string, vector<string>>("zang", vector<string>({"z", "ang"}))},
    {pair<string, vector<string>>("zao", vector<string>({"z", "ao"}))},
    {pair<string, vector<string>>("ze", vector<string>({"z", "e"}))},
    {pair<string, vector<string>>("zei", vector<string>({"z", "ei"}))},
    {pair<string, vector<string>>("zen", vector<string>({"z", "en"}))},
    {pair<string, vector<string>>("zeng", vector<string>({"z", "eng"}))},
    {pair<string, vector<string>>("zha", vector<string>({"zh", "a"}))},
    {pair<string, vector<string>>("zhai", vector<string>({"zh", "ai"}))},
    {pair<string, vector<string>>("zhan", vector<string>({"zh", "an"}))},
    {pair<string, vector<string>>("zhang", vector<string>({"zh", "ang"}))},
    {pair<string, vector<string>>("zhao", vector<string>({"zh", "ao"}))},
    {pair<string, vector<string>>("zhe", vector<string>({"zh", "e"}))},
    {pair<string, vector<string>>("zhei", vector<string>({"zh", "ei"}))},
    {pair<string, vector<string>>("zhen", vector<string>({"zh", "en"}))},
    {pair<string, vector<string>>("zheng", vector<string>({"zh", "eng"}))},
    {pair<string, vector<string>>("zhi", vector<string>({"zh", "iii"}))},
    {pair<string, vector<string>>("zhong", vector<string>({"zh", "ong"}))},
    {pair<string, vector<string>>("zhou", vector<string>({"zh", "ou"}))},
    {pair<string, vector<string>>("zhu", vector<string>({"zh", "u"}))},
    {pair<string, vector<string>>("zhua", vector<string>({"zh", "ua"}))},
    {pair<string, vector<string>>("zhuai", vector<string>({"zh", "uai"}))},
    {pair<string, vector<string>>("zhuan", vector<string>({"zh", "uan"}))},
    {pair<string, vector<string>>("zhuang", vector<string>({"zh", "uang"}))},
    {pair<string, vector<string>>("zhui", vector<string>({"zh", "uei"}))},
    {pair<string, vector<string>>("zhun", vector<string>({"zh", "uen"}))},
    {pair<string, vector<string>>("zhuo", vector<string>({"zh", "uo"}))},
    {pair<string, vector<string>>("zi", vector<string>({"z", "ii"}))},
    {pair<string, vector<string>>("zong", vector<string>({"z", "ong"}))},
    {pair<string, vector<string>>("zou", vector<string>({"z", "ou"}))},
    {pair<string, vector<string>>("zu", vector<string>({"z", "u"}))},
    {pair<string, vector<string>>("zuan", vector<string>({"z", "uan"}))},
    {pair<string, vector<string>>("zui", vector<string>({"z", "uei"}))},
    {pair<string, vector<string>>("zun", vector<string>({"z", "uen"}))},
    {pair<string, vector<string>>("zuo", vector<string>({"z", "uo"}))}};

    return pingyin2PhoneMap;

}


